# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('courseid', models.AutoField(db_column='CourseID', primary_key=True, serialize=False)),
                ('coursename', models.CharField(db_column='CourseName', max_length=50)),
                ('departmentid', models.IntegerField(db_column='DepartmentID')),
                ('credit', models.IntegerField(db_column='Credit')),
                ('coursescheduleid', models.IntegerField(db_column='CourseScheduleID')),
            ],
            options={
                'db_table': 'COURSE',
            },
        ),
        migrations.CreateModel(
            name='CoursePrecourse',
            fields=[
                ('courseprecourseid', models.AutoField(db_column='CoursePreCourseID', primary_key=True, serialize=False)),
                ('courseid', models.IntegerField(db_column='CourseID')),
                ('precourseid', models.IntegerField(db_column='PreCourseID')),
            ],
            options={
                'db_table': 'COURSE_PRECOURSE',
            },
        ),
        migrations.CreateModel(
            name='Courseschedule',
            fields=[
                ('coursescheduleid', models.AutoField(db_column='CourseScheduleID', primary_key=True, serialize=False)),
                ('quarterid', models.IntegerField(db_column='QuarterID')),
                ('year', models.IntegerField(db_column='Year')),
            ],
            options={
                'db_table': 'COURSESCHEDULE',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('departmentid', models.AutoField(db_column='DepartmentID', primary_key=True, serialize=False)),
                ('departmentname', models.CharField(db_column='DepartmentName', max_length=50)),
                ('departmentshortname', models.CharField(db_column='DepartmentShortName', max_length=10)),
            ],
            options={
                'db_table': 'DEPARTMENT',
            },
        ),
        migrations.CreateModel(
            name='Quarter',
            fields=[
                ('quarterid', models.AutoField(db_column='QuarterID', primary_key=True, serialize=False)),
                ('quartername', models.CharField(db_column='QuarterName', max_length=10)),
                ('quartershortname', models.CharField(db_column='QUarterShortName', max_length=10)),
            ],
            options={
                'db_table': 'QUARTER',
            },
        ),
    ]
