# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 15:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_dubhack', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('classid', models.AutoField(db_column='ClassID', primary_key=True, serialize=False)),
                ('credit', models.IntegerField(db_column='Credit')),
            ],
            options={
                'db_table': 'CLASS',
            },
        ),
        migrations.CreateModel(
            name='Coursetype',
            fields=[
                ('coursetypeid', models.AutoField(db_column='CourseTypeID', primary_key=True, serialize=False)),
                ('coursetypename', models.CharField(db_column='CourseTypeName', max_length=50)),
            ],
            options={
                'db_table': 'COURSETYPE',
            },
        ),
        # migrations.CreateModel(
        #     name='MajorRequirements',
        #     fields=[
        #         ('majorid', models.AutoField(db_column='MajorRequirements', primary_key=True, serialize=False)),
        #         ('majorname', models.CharField(db_column='MajorRequirementsName', max_length=50)),
        #     ],
        #     options={
        #         'db_table': 'MAJOR_REQUIREMENTS',
        #     },
        # ),
        migrations.RemoveField(
            model_name='course',
            name='coursescheduleid',
        ),
        migrations.RemoveField(
            model_name='course',
            name='credit',
        ),
        migrations.RemoveField(
            model_name='courseprecourse',
            name='courseid',
        ),
        migrations.AddField(
            model_name='course',
            name='coursenumber',
            field=models.IntegerField(db_column='CourseNumber', default=999),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='departmentid',
            field=models.ForeignKey(db_column='DepartmentID', on_delete=django.db.models.deletion.DO_NOTHING, to='app_dubhack.Department'),
        ),
        migrations.AlterField(
            model_name='courseprecourse',
            name='precourseid',
            field=models.ForeignKey(db_column='PreCourseID', on_delete=django.db.models.deletion.DO_NOTHING, to='app_dubhack.Course'),
        ),
        migrations.AlterField(
            model_name='department',
            name='departmentshortname',
            field=models.CharField(blank=True, db_column='DepartmentShortName', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='courseid',
            field=models.ForeignKey(db_column='CourseID', on_delete=django.db.models.deletion.DO_NOTHING, to='app_dubhack.Course'),
        ),
        migrations.AddField(
            model_name='class',
            name='coursescheduleid',
            field=models.ForeignKey(db_column='CourseScheduleID', on_delete=django.db.models.deletion.DO_NOTHING, to='app_dubhack.Courseschedule'),
        ),
        migrations.AddField(
            model_name='course',
            name='coursetypeid',
            field=models.ForeignKey(db_column='CourseTypeID', default=999, on_delete=django.db.models.deletion.DO_NOTHING, to='app_dubhack.Coursetype'),
            preserve_default=False,
        ),
    ]
