# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 19:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_dubhack', '0003_majorrequirements'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inputShortName', models.CharField(db_column='InportShortName', max_length=25)),
                ('inputShortNumber', models.IntegerField(db_column='InportShortNumber')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'USER_DATA',
            },
        ),
        migrations.AddField(
            model_name='majorrequirements',
            name='majornumber',
            field=models.IntegerField(db_column='MajorRequirementsNumber', default=99),
            preserve_default=False,
        ),
    ]
