# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 19:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_dubhack', '0004_auto_20161016_1203'),
    ]

    # operations = [
    #     migrations.RemoveField(
    #         model_name='majorrequirements',
    #         name='majornumber',
    #     ),
    # ]
