# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 19:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_dubhack', '0005_remove_majorrequirements_majornumber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MajorRequirements',
        ),
    ]
