# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_dubhack', '0006_delete_majorrequirements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='inputShortName',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='inputShortNumber',
        ),
        migrations.AddField(
            model_name='userdata',
            name='imputShortName',
            field=models.CharField(db_column='ImportShortName', default=999, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdata',
            name='imputShortNumber',
            field=models.IntegerField(db_column='ImportShortNumber', default=999),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quarter',
            name='quartershortname',
            field=models.CharField(db_column='QuarterShortName', max_length=10),
        ),
    ]
